version: 2
jobs:
  build:
    working_directory: ~/GraphQL.Client/
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      
      # Test
      - restore_cache:
          key: NUGET
      - run: dotnet test ./tests/GraphQL.Common.Tests/GraphQL.Common.Tests.csproj
      - run: dotnet test ./tests/GraphQL.Client.Tests/GraphQL.Client.Tests.csproj
      - save_cache:
          key: NUGET
          paths:
            - ~/.nuget/

      # Pack
      - run: dotnet build --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet build --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj
