name: Main workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet tool restore
    - run: dotnet build -c Release

  test:
    name: Test
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet test -c Release -p:ParallelizeTestCollections=false

  publish:
    name: Publish
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet build -c Release
    - run: dotnet nuget push ./src/GraphQL.Primitives/bin/Release/GraphQL.Primitives.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY/index.json
    - run: dotnet nuget push ./src/GraphQL.Client/bin/Release/GraphQL.Client.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY/index.json
    - run: dotnet nuget push ./src/GraphQL.Client.Http/bin/Release/GraphQL.Client.Http.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY/index.json
