name: Main workflow
on: [push]
jobs:
  generateVersionInfo:  
    name: GenerateVersionInfo
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet environment
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Fetch complete repository 
      run: git fetch
    - name: Generate version info from git history
      run: dotnet dotnet-gitversion /output json | Out-File gitversion.json; Get-Content gitversion.json
    - name: Upload version info file
      uses: actions/upload-artifact@v1
      with:
        name: gitversion
        path: gitversion.json

  build:
    name: Build
    needs: generateVersionInfo
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet environment
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - name: Download version info file
      uses: actions/download-artifact@v1
      with:
        name: gitversion
        path: ./
    - name: Inject version info into environment
      run: Get-Content gitversion.json | ConvertFrom-Json | ForEach-Object { foreach ($item in $_.PSObject.properties) { "::set-env name=GitVersion_$($item.Name)::$($item.Value)" } }; $env:GitVersion_SemVer
    - name: Build solution
      run: dotnet build -c Release
    - name: Create NuGet packages
      run: dotnet pack -c Release --no-build -o nupkg 
    - name: Upload nuget packages
      uses: actions/upload-artifact@v1
      with:
        name: nupkg
        path: nupkg

  test:
    name: Test
    needs: [build, generateVersionInfo]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet environment
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - name: Download version info file
      uses: actions/download-artifact@v1
      with:
        name: gitversion
        path: ./
    - name: Inject version info into environment
      run: Get-Content gitversion.json | ConvertFrom-Json | ForEach-Object { foreach ($item in $_.PSObject.properties) { "::set-env name=GitVersion_$($item.Name)::$($item.Value)" } }
    - name: Run tests
      run: dotnet test -c Release -p:ParallelizeTestCollections=false

  publish:
    name: Publish
    needs: [test, generateVersionInfo]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download nuget packages
      uses: actions/download-artifact@v1
      with:
        name: nupkg
    - name: Setup GitHub Packages as nuget source
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
        source-url: https://nuget.pkg.github.com/graphql-dotnet/index.json      
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # run: nuget source Add -Name "GPR" -Source "https://nuget.pkg.github.com/graphql-dotnet/index.json" -UserName graphql-dotnet -Password ${{ secrets.GITHUB_TOKEN }}          
    - name: push packages
      run: dotnet nuget push .\nupkg\*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    