name: Main workflow
on: [push]
jobs:
  build:
    container: mcr.microsoft.com/dotnet/core/sdk:3.0
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet tool restore
    - run: dotnet format --check --dry-run
    - run: dotnet restore
    - run: dotnet build
  test:
    container: mcr.microsoft.com/dotnet/core/sdk:3.0
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet test
  publish:
    container: mcr.microsoft.com/dotnet/core/sdk:3.0
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet pack
